---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
  notify: Start Nginx service
  tags:
    - lighthouse

- name: Install nodejs
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
  tags:
    - lighthouse

- name: install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present
  tags: 
    - lighthouse

- name: clone lighthouse
  become: true
  ansible.builtin.git:
    repo: "{{ repo_lighthouse }}"
    dest: "{{ dest_lighthouse }}"
    single_branch: true
    version: master
  tags:
    - lighthouse

- name: setup nginx conf
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Start Nginx service
  tags: 
    - lighthouse
