---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
  tags:
    - clickhouse

- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Start vector service
      ansible.builtin.service:
        name: vector
        state: restarted
      tags:
        - vector
        - restartservice

  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector-{{ vector_version }}.deb"
        mode: '0644'
      tags:
        - vector
        - distr

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install vector
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/vector-{{ vector_version }}.deb"
      changed_when: false
      tags:
        - vector
        - distr

    - name: Deploy vector configuration
      ansible.builtin.template:
        src: templates/vector.yml.j2
        dest: "{{ vector_config_path }}"
        mode: '0644'
      notify: Start vector service
      tags:
        - vector
        - config

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - vector
        - restart service

- name: Install lighthouse
  hosts: lighthouse
  tags:
    - lighthouse
    - install-lighthouse

  handlers:
    - name: Start Nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
      tags:
        - lighthouse

  tasks:
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: Start Nginx service
      tags:
        - lighthouse

    - name: Install nodejs
      become: true
      ansible.builtin.apt:
        name: nodejs
        state: present
        tags:
          - lighthouse

    - name: install git
      become: true
      ansible.builtin.apt:
        name: git
        state: present
        tags: 
          - lighthouse

    - name: clone lighthouse
      become: true
      ansible.builtin.git:
        repo: "{{ repo_lighthouse }}"
        dest: "{{ dest_lighthouse }}"
        single_branch: true
        version: master
        tags:
          - lighthouse

    - name: setup nginx conf
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: Start Nginx service
      tags: 
        - lighthouse